const exchangeLogos = {
	NasdaqNM: 'https://s3-symbol-logo.tradingview.com/country/US.svg',
	NYSE: 'https://s3-symbol-logo.tradingview.com/country/US.svg',
	NCM: 'https://s3-symbol-logo.tradingview.com/country/US.svg',
};

exports.getExchangeLogoUrl = function (exchangeName) {
	return exchangeLogos[exchangeName];
};

const baseUrl = 'https://s3-symbol-logo.tradingview.com/';

const symbolLogoNames = {
	A: 'agilent-technologies.svg',
	AA: 'alcoa.svg',
	AAL: 'american-airlines-group.svg',
	AAPL: 'apple.svg',
	ABBV: 'abbvie.svg',
	ABT: 'abbott.svg',
	// ACHN: '.svg',
	ACI: 'albertsons.svg',
	ACN: 'accenture.svg',
	ADBE: 'adobe.svg',
	ADSK: 'autodesk.svg',
	AEO: 'american-eagle-outfitters.svg',
	AGNC: 'agnc-investment.svg',
	AIG: 'american-international-group.svg',
	AKAM: 'akamai.svg',
	// ALXN: '.svg',
	AMAT: 'applied-materials.svg',
	AMD: 'advanced-micro-devices.svg',
	AMGN: 'amgen.svg',
	AMZN: 'amazon.svg',
	ANF: 'abercrombie-and-fitch.svg',
	// ANR: '.svg',
	APA: 'apa-corporation.svg',
	// APC: '.svg',
	ARC: 'arc-document-solutions.svg',
	// ARIA: '.svg',
	// ARNA: '.svg',
	ARR: 'armour-residential-reit-7-series-c-cumulative-redeemable-preferred-stock-liquidation-preference-2500-per-share.svg',
	// AUXL: '.svg',
	AVGO: 'broadcom.svg',
	// AVNR: '.svg',
	// AWAY: '.svg',
	AXP: 'american-express.svg',
	AZO: 'autozone.svg',
	BA: 'boeing.svg',
	BAC: 'bank-of-america.svg',
	BAX: 'baxter.svg',
	BBBY: 'bed-bath-and-beyond.svg',
	// BBT: '.svg',
	BBY: 'best-buy.svg',
	BIDU: 'baidu.svg',
	BIIB: 'biogen.svg',
	BK: 'bank-of-new-york-mellon.svg',
	BLK: 'blackrock.svg',
	BMY: 'bristol-myers-squibb.svg',
	BP: 'bp.svg',
	// BRCD: '.svg',
	// BRCM: '.svg',
	BTU: 'peabody-energy.svg',
	C: 'citigroup.svg',
	CHK: 'chesapeake-energy.svg',
	CNP: 'centerpoint-energy.svg',
	CSCO: 'cisco.svg',
	D: 'dominion-energy.svg',
	DAL: 'delta-air-lines.svg',
	// DBD: '.svg',
	DD: 'dupont-de-nemours.svg',
	DDD: '3-d-systems.svg',
	DE: 'deere.svg',
	DECK: 'deckers-outdoor.svg',
	DEI: 'douglas-emmett.svg',
	DHI: 'dr-horton.svg',
	DIS: 'walt-disney.svg',
	DLTR: 'dollar-tree.svg',
	// DNDN: '.svg',
	DO: 'diamond-offshore-drilling.svg',
	DOV: 'dover.svg',
	DOW: 'dow.svg',
	DRI: 'darden.svg',
	DV: 'doubleverify.svg',
	DVN: 'devon-energy.svg',
	EA: 'electronic-arts.svg',
	EBAY: 'ebay.svg',
	EBIX: 'ebix.svg',
	// ECYT: '.svg',
	ED: 'consolidated-edison.svg',
	// EMC: '.svg',
	// ENT: '.svg',
	ESI: 'element-solutions.svg',
	// ESRX: '.svg',
	// ETFC: '.svg',
	EXC: 'exelon.svg',
	EXPE: 'expedia.svg',
	F: 'ford.svg',
	FCEL: 'fuelcell-energy.svg',
	// GALE: '.svg',
	GD: 'general-dynamics.svg',
	GE: 'general-electric.svg',
	// GTAT: '.svg',
	HD: 'home-depot.svg',
	IBM: 'international-bus-mach.svg',
	INTC: 'intel.svg',
	JPM: 'jpmorgan-chase.svg',
	// KERX: '.svg',
	KO: 'coca-cola.svg',
	LLY: 'eli-lilly.svg',
	LUV: 'southwest.svg',
	MCD: 'mcdonalds.svg',
	MNST: 'monster-beverage.svg',
	MO: 'altria.svg',
	MSFT: 'microsoft.svg',
	NLY: 'annaly-capital-management.svg',
	NUS: 'nu-skin-enterprises.svg',
	OLED: 'universal-display.svg',
	// PNRA: '.svg',
	RAD: 'rite-aid.svg',
	SAM: 'boston-beer-co.svg',
	// SCTY: '.svg',
	SD: 'sandridge-energy.svg',
	STZ: 'constellation-brands.svg',
	T: 'at-and-t.svg',
	UA: 'under-armour.svg',
	USB: 'us-bancorp.svg',
	VZ: 'verizon.svg',
	WDC: 'western-digital.svg',
	WFC: 'wells-fargo.svg',
	// WLT: '.svg',
	XOM: 'exxon.svg',
};

exports.getSymbolLogos = function (name) {
    const image = symbolLogoNames[name];
    if (!image) return undefined;
	return [baseUrl + image];
};
